/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZkpRouteImport } from './routes/zkp'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiZkpRouteImport } from './routes/api/zkp'
import { Route as ApiWorkflowsRouteImport } from './routes/api/workflows'
import { Route as ApiThreatsRouteImport } from './routes/api/threats'
import { Route as ApiTargetsRouteImport } from './routes/api/targets'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBillingRouteImport } from './routes/api/billing'
import { Route as ApiWorkflowsOnboardingRouteImport } from './routes/api/workflows/onboarding'
import { Route as ApiWorkflowsChallengeRouteImport } from './routes/api/workflows/challenge'
import { Route as ApiWorkflowsAnalysisRouteImport } from './routes/api/workflows/analysis'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiConsoleHintRouteImport } from './routes/api/console/hint'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth/github/callback'

const ZkpRoute = ZkpRouteImport.update({
  id: '/zkp',
  path: '/zkp',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZkpRoute = ApiZkpRouteImport.update({
  id: '/api/zkp',
  path: '/api/zkp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsRoute = ApiWorkflowsRouteImport.update({
  id: '/api/workflows',
  path: '/api/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreatsRoute = ApiThreatsRouteImport.update({
  id: '/api/threats',
  path: '/api/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTargetsRoute = ApiTargetsRouteImport.update({
  id: '/api/targets',
  path: '/api/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingRoute = ApiBillingRouteImport.update({
  id: '/api/billing',
  path: '/api/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsOnboardingRoute = ApiWorkflowsOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ApiWorkflowsRoute,
} as any)
const ApiWorkflowsChallengeRoute = ApiWorkflowsChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => ApiWorkflowsRoute,
} as any)
const ApiWorkflowsAnalysisRoute = ApiWorkflowsAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => ApiWorkflowsRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleHintRoute = ApiConsoleHintRouteImport.update({
  id: '/api/console/hint',
  path: '/api/console/hint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGithubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/targets': typeof TargetsRoute
  '/threats': typeof ThreatsRoute
  '/zkp': typeof ZkpRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/targets': typeof ApiTargetsRoute
  '/api/threats': typeof ApiThreatsRoute
  '/api/workflows': typeof ApiWorkflowsRouteWithChildren
  '/api/zkp': typeof ApiZkpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/console/hint': typeof ApiConsoleHintRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/workflows/analysis': typeof ApiWorkflowsAnalysisRoute
  '/api/workflows/challenge': typeof ApiWorkflowsChallengeRoute
  '/api/workflows/onboarding': typeof ApiWorkflowsOnboardingRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/targets': typeof TargetsRoute
  '/threats': typeof ThreatsRoute
  '/zkp': typeof ZkpRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/targets': typeof ApiTargetsRoute
  '/api/threats': typeof ApiThreatsRoute
  '/api/workflows': typeof ApiWorkflowsRouteWithChildren
  '/api/zkp': typeof ApiZkpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/console/hint': typeof ApiConsoleHintRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/workflows/analysis': typeof ApiWorkflowsAnalysisRoute
  '/api/workflows/challenge': typeof ApiWorkflowsChallengeRoute
  '/api/workflows/onboarding': typeof ApiWorkflowsOnboardingRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/targets': typeof TargetsRoute
  '/threats': typeof ThreatsRoute
  '/zkp': typeof ZkpRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/targets': typeof ApiTargetsRoute
  '/api/threats': typeof ApiThreatsRoute
  '/api/workflows': typeof ApiWorkflowsRouteWithChildren
  '/api/zkp': typeof ApiZkpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/console/hint': typeof ApiConsoleHintRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/workflows/analysis': typeof ApiWorkflowsAnalysisRoute
  '/api/workflows/challenge': typeof ApiWorkflowsChallengeRoute
  '/api/workflows/onboarding': typeof ApiWorkflowsOnboardingRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/console'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/projects'
    | '/prompts'
    | '/sitemap.xml'
    | '/targets'
    | '/threats'
    | '/zkp'
    | '/api/billing'
    | '/api/chat'
    | '/api/leaderboard'
    | '/api/targets'
    | '/api/threats'
    | '/api/workflows'
    | '/api/zkp'
    | '/auth/callback'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/console/hint'
    | '/api/dashboard/stats'
    | '/api/webhooks/stripe'
    | '/api/workflows/analysis'
    | '/api/workflows/challenge'
    | '/api/workflows/onboarding'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/console'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/projects'
    | '/prompts'
    | '/sitemap.xml'
    | '/targets'
    | '/threats'
    | '/zkp'
    | '/api/billing'
    | '/api/chat'
    | '/api/leaderboard'
    | '/api/targets'
    | '/api/threats'
    | '/api/workflows'
    | '/api/zkp'
    | '/auth/callback'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/console/hint'
    | '/api/dashboard/stats'
    | '/api/webhooks/stripe'
    | '/api/workflows/analysis'
    | '/api/workflows/challenge'
    | '/api/workflows/onboarding'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/console'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/projects'
    | '/prompts'
    | '/sitemap.xml'
    | '/targets'
    | '/threats'
    | '/zkp'
    | '/api/billing'
    | '/api/chat'
    | '/api/leaderboard'
    | '/api/targets'
    | '/api/threats'
    | '/api/workflows'
    | '/api/zkp'
    | '/auth/callback'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/console/hint'
    | '/api/dashboard/stats'
    | '/api/webhooks/stripe'
    | '/api/workflows/analysis'
    | '/api/workflows/challenge'
    | '/api/workflows/onboarding'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  ConsoleRoute: typeof ConsoleRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptsRoute: typeof PromptsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TargetsRoute: typeof TargetsRoute
  ThreatsRoute: typeof ThreatsRoute
  ZkpRoute: typeof ZkpRoute
  ApiBillingRoute: typeof ApiBillingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiTargetsRoute: typeof ApiTargetsRoute
  ApiThreatsRoute: typeof ApiThreatsRoute
  ApiWorkflowsRoute: typeof ApiWorkflowsRouteWithChildren
  ApiZkpRoute: typeof ApiZkpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRouteWithChildren
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiConsoleHintRoute: typeof ApiConsoleHintRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zkp': {
      id: '/zkp'
      path: '/zkp'
      fullPath: '/zkp'
      preLoaderRoute: typeof ZkpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zkp': {
      id: '/api/zkp'
      path: '/api/zkp'
      fullPath: '/api/zkp'
      preLoaderRoute: typeof ApiZkpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows': {
      id: '/api/workflows'
      path: '/api/workflows'
      fullPath: '/api/workflows'
      preLoaderRoute: typeof ApiWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threats': {
      id: '/api/threats'
      path: '/api/threats'
      fullPath: '/api/threats'
      preLoaderRoute: typeof ApiThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/targets': {
      id: '/api/targets'
      path: '/api/targets'
      fullPath: '/api/targets'
      preLoaderRoute: typeof ApiTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing': {
      id: '/api/billing'
      path: '/api/billing'
      fullPath: '/api/billing'
      preLoaderRoute: typeof ApiBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/onboarding': {
      id: '/api/workflows/onboarding'
      path: '/onboarding'
      fullPath: '/api/workflows/onboarding'
      preLoaderRoute: typeof ApiWorkflowsOnboardingRouteImport
      parentRoute: typeof ApiWorkflowsRoute
    }
    '/api/workflows/challenge': {
      id: '/api/workflows/challenge'
      path: '/challenge'
      fullPath: '/api/workflows/challenge'
      preLoaderRoute: typeof ApiWorkflowsChallengeRouteImport
      parentRoute: typeof ApiWorkflowsRoute
    }
    '/api/workflows/analysis': {
      id: '/api/workflows/analysis'
      path: '/analysis'
      fullPath: '/api/workflows/analysis'
      preLoaderRoute: typeof ApiWorkflowsAnalysisRouteImport
      parentRoute: typeof ApiWorkflowsRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/console/hint': {
      id: '/api/console/hint'
      path: '/api/console/hint'
      fullPath: '/api/console/hint'
      preLoaderRoute: typeof ApiConsoleHintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof ApiAuthGithubRoute
    }
  }
}

interface ApiWorkflowsRouteChildren {
  ApiWorkflowsAnalysisRoute: typeof ApiWorkflowsAnalysisRoute
  ApiWorkflowsChallengeRoute: typeof ApiWorkflowsChallengeRoute
  ApiWorkflowsOnboardingRoute: typeof ApiWorkflowsOnboardingRoute
}

const ApiWorkflowsRouteChildren: ApiWorkflowsRouteChildren = {
  ApiWorkflowsAnalysisRoute: ApiWorkflowsAnalysisRoute,
  ApiWorkflowsChallengeRoute: ApiWorkflowsChallengeRoute,
  ApiWorkflowsOnboardingRoute: ApiWorkflowsOnboardingRoute,
}

const ApiWorkflowsRouteWithChildren = ApiWorkflowsRoute._addFileChildren(
  ApiWorkflowsRouteChildren,
)

interface ApiAuthGithubRouteChildren {
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
}

const ApiAuthGithubRouteChildren: ApiAuthGithubRouteChildren = {
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
}

const ApiAuthGithubRouteWithChildren = ApiAuthGithubRoute._addFileChildren(
  ApiAuthGithubRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  ConsoleRoute: ConsoleRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  PromptsRoute: PromptsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TargetsRoute: TargetsRoute,
  ThreatsRoute: ThreatsRoute,
  ZkpRoute: ZkpRoute,
  ApiBillingRoute: ApiBillingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiTargetsRoute: ApiTargetsRoute,
  ApiThreatsRoute: ApiThreatsRoute,
  ApiWorkflowsRoute: ApiWorkflowsRouteWithChildren,
  ApiZkpRoute: ApiZkpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAuthGithubRoute: ApiAuthGithubRouteWithChildren,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiConsoleHintRoute: ApiConsoleHintRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
